apiVersion: prometheus.io/v1alpha1
kind: Prometheus
metadata:
  namespaces: prometheus
  name: prometheus
  labels:
    app: prometheus
spec:
  statefulset:
    replicas: 1
    initImage: "busybox:latest"
    imagePullPolicy: "IfNotPresent"
    reloadImage:  "jimmidyson/configmap-reload:v0.1"
    image: "prom/prometheus:v2.2.1"
    storageClassName: "local-storage"
status:
